---
title: "Patterns in Knowledge Production in Sweden and Finland, 1640–1828"
author: "Mikko Tolonen, Jani Marjanen, Hege Roivainen, Leo Lahti"
date: date: "`r Sys.Date()`"
output: markdown_document
---


```{r init, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.path = "figure-2016-manuscript/", dev="CairoPNG")
# Set locale
tmp <- Sys.setlocale(locale="UTF-8") 

library(stringr)
library(dplyr)
library(ggplot2)
library(bibliographica)
library(fennica)
library(sorvi)

# Nice theme
theme_set(theme_bw(26))

# Read data
dfo <- readRDS("df.Rds")

# Analysis time window
#dfo <- dfo %>% filter(publication_year >= 1640 & publication_year <= 1828)
dfo <- dfo %>% filter(publication_year >= 1640 & publication_year <= 1911)

# Calculate title length (word count)
dfo$title_wordcount <- sapply(strsplit(as.character(dfo$title), " "), length)
dfo$title_wordcount[is.na(dfo$title)] <- NA
```


```{r title_length, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=7, fig.width=15}
df <- dfo %>% group_by(publication_year) %>%
              summarize(median_title_length = median(title_wordcount),
	      		mean_title_length = mean(title_wordcount),
	      		n = n())

p1 <- ggplot(df, aes(x = publication_year, y = mean_title_length)) +
       geom_point(aes(size = n)) + geom_smooth() + ggtitle("Mean title word count")
p2 <- ggplot(df, aes(x = publication_year, y = median_title_length)) +
       geom_point(aes(size = n)) + geom_smooth() +
       ggtitle("Median title word count")       

library(gridExtra)
grid.arrange(p1, p2, nrow = 1)
```






```{r title_length_by_gatherings, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=7, fig.width=15}
top.gatherings <- setdiff(names(top(dfo, "gatherings", 5)), "NA")

df <- dfo %>% filter(gatherings %in% top.gatherings) %>%
              group_by(publication_year, gatherings) %>%
              summarize(mean_title_length = mean(title_wordcount),
	      		n = n())

p <- ggplot(df, aes(x = publication_year, y = mean_title_length,
                     fill = gatherings, color = gatherings)) +
       geom_point(aes(size = n)) +
       geom_smooth() +
       scale_y_log10() +
       ggtitle("Mean title word count (top gatherings)")

print(p)
```




```{r title_length_by_lang, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=7, fig.width=15}
top.language <- setdiff(names(top(dfo, "language", 10)), "NA")

df <- dfo %>% filter(language %in% top.language) %>%
              group_by(publication_decade, language) %>%
              summarize(mean_title_length = mean(title_wordcount),
	      		n = n())

p <- ggplot(df, aes(x = publication_decade, y = mean_title_length,
                     fill = language, color = language)) +
       geom_point(aes(shape = language, size = n)) +
       geom_line(aes(linetype = language), size = 1) +
       #scale_y_log10() +
       ggtitle("Mean title word count (top language)")

print(p)
```






